AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  DisabledByDefault: true

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: true

Style/DotPosition:
  EnforcedStyle: leading

Style/AlignHash:
  Enabled: true

Style/ExtraSpacing:
  AllowForAlignment: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
